
GET http://localhost:3003/users
Content-Type: application/json

###

GET http://localhost:3003/products
Content-Type: application/json

###

POST http://localhost:3003/users
content-type: application/json

{
    "name": "João",
    "email": "jojo@email.com",
    "password": "12340"
}

### 

POST http://localhost:3003/products
content-type: application/json

{
    "name": "Pedaco de queijo",
    "price": 40,
    "image_url": "www.urldaimg.com/imagem.jpg"
}

### 